# Site settings
title: Web Development Journey
header-img: img/home-bg.png
email: navystylz@gmail.com
copyright_name: Navystylz
description: > # this means to ignore newlines until "baseurl:"
  Staying Relevant With New Trends & Techniques
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Navystylz
learn_profile: Navystylz
email_username: navystylz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
